# Generated by Django 5.1.1 on 2024-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='temp_field',
            field=models.BooleanField(default=True),
        ),
    ]
