# Generated by Django 5.1.1 on 2024-11-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='temp_field',
        ),
    ]
